version: '2'
services:
    myjhipsterblog-app:
        image: myjhipsterblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myjhipsterblog-mysql:3306/myjhipsterblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myjhipsterblog-mysql:
        extends:
            file: mysql.yml
            service: myjhipsterblog-mysql
